### ISSUE TITLE
hard to run on MacOS without Anaconda because of a bug in matplotlib

### ISSUE THREAD

**Issue by lenzai** [coderbunker-100daysofcode/100daysofcode#4]
reference: https://matplotlib.org/faq/osx_framework.html

```
(venv) (base) OSs-MacBook-Pro:100daysofcode fredericbazin$ python Github_scrap_for_reports.py 
Traceback (most recent call last):
  File "Github_scrap_for_reports.py", line 9, in <module>
    import matplotlib.pyplot as plt
  File "/Users/fredericbazin/ws/100daysofcode/venv/lib/python3.7/site-packages/matplotlib/pyplot.py", line 2372, in <module>
    switch_backend(rcParams["backend"])
  File "/Users/fredericbazin/ws/100daysofcode/venv/lib/python3.7/site-packages/matplotlib/pyplot.py", line 207, in switch_backend
    backend_mod = importlib.import_module(backend_name)
  File "/usr/local/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/fredericbazin/ws/100daysofcode/venv/lib/python3.7/site-packages/matplotlib/backends/backend_macosx.py", line 14, in <module>
    from matplotlib.backends import _macosx
ImportError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are using (Ana)Conda please install python.app and replace the use of 'python' with 'pythonw'. See 'Working with Matplotlib on OSX' in the Matplotlib FAQ for more information.
```

**Comment by ansufei** [comment]
Good to know, thanks. I was hesitating to use Matplotlib or seaborn for the visualization, I'll switch to seaborn then.

**Comment by lenzai** [comment]
seaborn is a layer on top of matplot.lib.

How about Google sheets?
